---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vermas71 # Roche userId
spec:
  profile:
    displayName: Sunil Verma1
    email: sunil1.verma@roche.com # Roche email
  memberOf: [sw_engineering_horizontals]
  type: User
  owner: john@example.com
  lifecycle: experimental
---
